{% set version = "3.1.1" %}

package:
  name: cloudpickle
  version: {{ version }}

source:
  fn: cloudpickle-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/c/cloudpickle/cloudpickle-{{ version }}.tar.gz
  sha256: b216fa8ae4019d5482a8ac3c95d8f6346115d8835911fd4aefd1a445e4242c64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core

  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - cloudpickle
  commands:
    - pip check

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Extended pickling support for Python objects
  description: |
    cloudpickle is extended pickling support for Python objects.
    cloudpickle makes it possible to serialize Python constructs not
    supported by the default pickle module from the Python standard library.
  doc_url: https://pypi.python.org/pypi/cloudpickle/{{ version }}
  doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
  dev_url: https://github.com/cloudpipe/cloudpickle

extra:
  recipe-maintainers:
    - jakirkham
    - ogrisel
    - rgbkrk
    - mrocklin
    - nehaljwani
